spring.datasource.url=jdbc:postgresql://localhost:5432/procurewatch
spring.datasource.username=postgres
spring.datasource.password=test123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Important: never seed PostgreSQL automatically
spring.sql.init.mode=never
spring.h2.console.enabled=false

logging.level.org.hibernate.SQL=warn
logging.level.org.hibernate.orm.jdbc.bind=warn