# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/procurewatch
spring.datasource.username=postgres
spring.datasource.password=test123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# IMPORTANT: turn off SQL spam
logging.level.org.hibernate.SQL=warn
logging.level.org.hibernate.orm.jdbc.bind=warn

# H2 console OFF when using PostgreSQL
spring.h2.console.enabled=false

# Usually not needed for PostgreSQL unless you have schema.sql/data.sql
spring.sql.init.mode=never