spring.application.name=procurewatch-backend

# Server
server.port=8080

# Default database profile
spring.profiles.active=postgres

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# JPA common settings
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# Logging common settings
logging.level.org.springframework.orm.jpa=warn
logging.level.org.springframework.transaction=warn

# Groq AI API
groq.api.key=${GROQ_API_KEY:}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.3-70b-versatile

logging.level.org.springframework.web.servlet.handler.HandlerMappingIntrospector=ERROR