# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:procurewatch;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Show SQL only in H2 mode
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

# If you have data.sql/schema.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always